# Generated by Django 5.2.3 on 2025-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rosbags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('mission_name', models.CharField(max_length=100)),
                ('number_of_laps_completed', models.IntegerField()),
                ('number_of_evaluated_cones_yellow', models.IntegerField()),
                ('number_of_evaluated_cones_blue', models.IntegerField()),
                ('is_successful', models.BooleanField(default=False)),
                ('rosbag_file', models.FileField(blank=True, null=True, upload_to='rosbags/')),
                ('avg_lap_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
