# Generated by Django 5.2.3 on 2025-06-30 17:05

import auto_tests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosbags',
            name='db_file',
            field=models.FileField(blank=True, null=True, upload_to=auto_tests.models.rosbag_upload_path),
        ),
        migrations.AddField(
            model_name='rosbags',
            name='yaml_file',
            field=models.FileField(blank=True, null=True, upload_to=auto_tests.models.rosbag_upload_path),
        ),
        migrations.AlterField(
            model_name='rosbags',
            name='rosbag_file',
            field=models.FileField(blank=True, null=True, upload_to='temp_zips/'),
        ),
    ]
