# Generated by Django 5.2.3 on 2025-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tests', '0002_rosbags_db_file_rosbags_yaml_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosbags',
            name='number_of_laps_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
