# Generated by Django 5.2.3 on 2025-07-02 10:07

import auto_tests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tests', '0003_alter_rosbags_number_of_laps_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosbags',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to=auto_tests.models.rosbag_upload_path),
        ),
    ]
