# Generated by Django 5.2.3 on 2025-07-03 19:29

import auto_tests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tests', '0004_rosbags_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosbags',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='temp_zips/'),
        ),
        migrations.AlterField(
            model_name='rosbags',
            name='rosbag_file',
            field=models.FileField(blank=True, null=True, upload_to=auto_tests.models.rosbag_upload_path),
        ),
    ]
