# Generated by Django 5.2.3 on 2025-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tests', '0005_rosbags_zip_file_alter_rosbags_rosbag_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosbags',
            name='number_of_evaluated_cones_unknown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rosbags',
            name='number_of_evaluated_cones_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rosbags',
            name='number_of_evaluated_cones_yellow',
            field=models.IntegerField(default=0),
        ),
    ]
